const ProfileActionTypes = {
  GET_PROFILE: "GET_PROFILE",
  GET_PROFILES: "GET_PROFILES",
  CLEAR_PROFILE: "CLEAR_PROFILE",
  PROFILE_ERROR: "PROFILE_ERROR",
  UPDATE_PROFILE: "UPDATE_PROFILE",
  GET_REPOS: "GET_REPOS"
};

export default ProfileActionTypes;
